events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        
        location / {
            fastcgi_pass server:8080;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}